meta_product_name: "TravelPaws"
meta_title: "TravelPaws - Travel with purpose"
meta_description: "Connect to local shelters & become a travel guardian for adopted animals."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@TravelPaws"   # required for Twitter Cards
